[package]
name = "gajibot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
http-body-util = "0.1.5"
hyper = "1.11.1"
hyper-rustls = { version =  "0.27.9", default-features = false, features = ["http1", "http2", "rustls-platform-verifier"] }
hyper-util = { version = "0.1.20", default-features = false, features = ["client-legacy", "http1", "http2", "tokio"] }
percent-encoding = "2.3.2"
rustls = { version = "0.23.44", default-features = false, features = ["ring"] }
twilight-gateway = "0.17.1"
twilight-http = "0.17.1"
twilight-model = "0.17.1"

[dependencies.tokio]
version = "1.53.1"
default-features = false
features = ["rt-multi-thread"]
