name: Build binary

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build-alpine:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # 2.9.2
        with:
          cache-targets: "false"
      - name: Install musl toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
          rustup toolchain install stable --profile minimal --target x86_64-unknown-linux-musl
      - name: Build binary
        run: cargo +stable build --locked --release --target x86_64-unknown-linux-musl --bin gajibot --features otel
      - name: Package binary
        run: tar -czf gajibot-alpine-x86_64.tar.gz -C target/x86_64-unknown-linux-musl/release gajibot
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: gajibot-alpine-x86_64
          path: gajibot-alpine-x86_64.tar.gz
          if-no-files-found: error
